language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements.txt"
script: ./tests/run_tests.sh
